version: '3.9'

services:
  mysql:
      image: mysql:8.0
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: password
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      networks:
        - laravel

networks:
  laravel:
    driver: bridge
volumes:
  mysql-data:
    driver: local